version: '3'
services:
  user_server:
    container_name: user_server
    build:
      context: ./US
      dockerfile: Dockerfile
    image: yc6380/us:latest
    ports:
      - "8080:8080"
    networks:
      - DCN_lab3      
  fibonacci_server:
    container_name: fibonacci_server
    build:
      context: ./FS
      dockerfile: Dockerfile
    image: yc6380/fs:latest
    ports:
      - "9090:9090"
    networks:
      - DCN_lab3
  auth_server:
    container_name: auth_server
    build:
      context: ./AS
      dockerfile: Dockerfile
    image: yc6380/as:latest
    ports:
      - "53533:53533/udp"
    networks:
      - DCN_lab3
networks:
  DCN_lab3:
    name: DCN_lab3
    driver: bridge
